arm = BodyGroup.create!(body_part: "Arms")
leg = BodyGroup.create!(body_part: "Legs")
core = BodyGroup.create!(body_part: "Core")
chest = BodyGroup.create!(body_part: "Chest")
shoulder = BodyGroup.create!(body_part: "Shoulder")
back = BodyGroup.create!(body_part: "Back")

tricep_dips = Workout.create!(img: "https://www.mensjournal.com/.image/c_limit%2Ccs_srgb%2Cq_auto:good%2Cw_620/MTk2MTM3MzIxNzgzMDQzNTg5/2-dip.webp", name: "tricep dips")
squat = Workout.create!(img: "https://i.pinimg.com/564x/f2/db/1f/f2db1f89cfc62c18643528a803295488.jpg", name: "Weighted Squats")
bench = Workout.create!(img: "https://i.pinimg.com/originals/a6/4d/df/a64ddf7b1d4775a7ca05302c0c31c881.gif", name: "Bench Press")
bulgarian_split_squat = Workout.create!(img: "https://hips.hearstapps.com/hmg-prod/images/split-squat-1541799833.jpg", name: "Bulgarian split squat")
leg_press = Workout.create!(img: "https://www.panattasport.com/resources/products/1sc085//01.jpg", name: "Leg press")
leg_curl = Workout.create!(img: "https://weighttraining.guide/wp-content/uploads/2016/10/lying-leg-curl-resized.png?ezimgfmt=ng%3Awebp%2Fngcb4", name: "Leg Curl")
calf_raises = Workout.create!(img: "https://hips.hearstapps.com/hmg-prod/images/angela-calf-exercises-main-1557866836.jpg?crop=0.625xw:1.00xh;0.211xw,0&resize=1200:*", name: "Calf raise'es")

muscle1 = Muscle.create!(name: "abdominals", body_group_id: core.id)
muscle2 = Muscle.create!(name: "abductors", body_group_id: leg.id)
muscle3 = Muscle.create!(name: "adductors", body_group_id: leg.id)
muscle4 = Muscle.create!(name: "biceps", body_group_id: arm.id)
muscle5 = Muscle.create!(name: "calves", body_group_id: leg.id)
muscle6 = Muscle.create!(name: "chest", body_group_id: chest.id)
muscle7 = Muscle.create!(name: "forearms", body_group_id: arm.id)
muscle8 = Muscle.create!(name: "glutes", body_group_id: leg.id)
muscle9 = Muscle.create!(name: "hamstrings", body_group_id: leg.id)
muscle10 = Muscle.create!(name: "lats", body_group_id: back.id)
muscle11 = Muscle.create!(name: "lower_back", body_group_id: back.id)
muscle12 = Muscle.create!(name: "middle_back", body_group_id: back.id)
muscle13 = Muscle.create!(name: "neck", body_group_id: shoulder.id)
muscle14 = Muscle.create!(name: "quadriceps", body_group_id: leg.id)
muscle15 = Muscle.create!(name: "traps", body_group_id: back.id)
muscle16 = Muscle.create!(name: "triceps", body_group_id: arm.id)

WorkoutMuscle.create!(workout_id: tricep_dips.id, muscle_id: muscle16.id)
WorkoutMuscle.create!(workout_id: squat.id, muscle_id: muscle14.id)
WorkoutMuscle.create!(workout_id: bulgarian_split_squat.id, muscle_id: muscle8.id)
WorkoutMuscle.create!(workout_id: leg_press.id, muscle_id: muscle14.id)
WorkoutMuscle.create!(workout_id: leg_curl.id, muscle_id: muscle9.id)
WorkoutMuscle.create!(workout_id: calf_raises.id, muscle_id: muscle5.id)
