arm = BodyGroup.create!(body_part: "Arms")
leg = BodyGroup.create!(body_part: "Legs")
core = BodyGroup.create!(body_part: "Core")
chest = BodyGroup.create!(body_part: "Chest")
shoulder = BodyGroup.create!(body_part: "Shoulder")
back = BodyGroup.create!(body_part: "Back")

tricep_dips = Workout.create!(img: "https://workoutlabs.com/train/svg.php?id=31392", name: "tricep dips")
squat = Workout.create!(img: "https://workoutlabs.com/train/svg.php?id=31012", name: "Weighted Squats")
bench = Workout.create!(img: "https://workoutlabs.com/train/svg.php?id=31020", name: "Bench Press")
bulgarian_split_squat = Workout.create!(img: "https://workoutlabs.com/train/svg.php?id=31248", name: "Bulgarian split squat")
leg_press = Workout.create!(img: "https://workoutlabs.com/train/svg.php?id=31792", name: "Leg press")
leg_curl = Workout.create!(img: "https://workoutlabs.com/train/svg.php?id=31820", name: "Leg Curl")
calf_raises = Workout.create!(img: "https://workoutlabs.com/train/svg.php?id=31172", name: "Calf raises")
ab_roller = Workout.create!(img: "https://workoutlabs.com/train/svg.php?id=30972", name: "Ab roller")
seated_tricep_dips = Workout.create!(img: "https://workoutlabs.com/train/svg.php?id=31000", name: "Seated Tricep Dips")
barbell_hip_thrusts = Workout.create!(img: "https://workoutlabs.com/train/svg.php?id=31060", name: "Barbell Hip Thrusts")
barbell_curls = Workout.create!(img: "https://workoutlabs.com/train/svg.php?id=31032", name: "Barbell Curls")
lying_oblique_reach = Workout.create!(img: "https://workoutlabs.com/train/svg.php?id=30980", name: "Lying Oblique Reach")
bear_crawl = Workout.create!(img: "https://workoutlabs.com/train/svg.php?id=31124", name: "Bear Crawl")
kickbacks = Workout.create!(img: "https://workoutlabs.com/train/svg.php?id=31168", name: "Alternaating Reach & Kickbacks")
bicycles = Workout.create!(img: "https://workoutlabs.com/train/svg.php?id=31164", name: "Bicycles")
machine_flyes = Workout.create!(img: "https://workoutlabs.com/train/svg.php?id=31260", name: "Machine Flyes")
cable_hammer_bicep_curls = Workout.create!(img: "https://workoutlabs.com/train/svg.php?id=31272", name: "Cable Hammer Bicep Curls")
hip_raises = Workout.create!(img: "https://workoutlabs.com/train/svg.php?id=31752", name: "Hip Raises")
dumbbell_flyes = Workout.create!(img: "https://workoutlabs.com/train/svg.php?id=31376", name: "Dumbbell Flyes")
lat_pulldown = Workout.create!(img: "https://workoutlabs.com/train/svg.php?id=31320", name: "Lat Pulldown")
barbell_clean_and_press = Workout.create!(img: "https://workoutlabs.com/train/svg.php?id=31100", name: "Barbell Clean and Press")
barbell_shoulder_press = Workout.create!(img: "https://workoutlabs.com/train/svg.php?id=31080", name: "Barbell Shoulder Press")
cable_upright_rows = Workout.create!(img: "https://workoutlabs.com/train/svg.php?id=32660", name: "Cable Upright Rows")
pullups = Workout.create!(img: "https://workoutlabs.com/train/svg.php?id=31324", name: "Pullups")
bar_rows = Workout.create!(img: "https://workoutlabs.com/train/svg.php?id=31156", name: "T-Bar Rows")
deadlifts = Workout.create!(img: "https://workoutlabs.com/train/svg.php?id=31036", name: "Barbell Deadlifts")
shoulder_shrugs = Workout.create!(img: "https://workoutlabs.com/train/svg.php?id=31084", name: "Shoulder Shrugs")

muscle1 = Muscle.create!(name: "abdominals", body_group_id: core.id)
muscle2 = Muscle.create!(name: "abductors", body_group_id: leg.id)
muscle3 = Muscle.create!(name: "adductors", body_group_id: leg.id)
muscle4 = Muscle.create!(name: "biceps", body_group_id: arm.id)
muscle5 = Muscle.create!(name: "calves", body_group_id: leg.id)
muscle6 = Muscle.create!(name: "chest", body_group_id: chest.id)
muscle7 = Muscle.create!(name: "forearms", body_group_id: arm.id)
muscle8 = Muscle.create!(name: "glutes", body_group_id: leg.id)
muscle9 = Muscle.create!(name: "hamstrings", body_group_id: leg.id)
muscle10 = Muscle.create!(name: "lats", body_group_id: back.id)
muscle11 = Muscle.create!(name: "lower_back", body_group_id: back.id)
muscle12 = Muscle.create!(name: "middle_back", body_group_id: back.id)
muscle13 = Muscle.create!(name: "neck", body_group_id: shoulder.id)
muscle14 = Muscle.create!(name: "quadriceps", body_group_id: leg.id)
muscle15 = Muscle.create!(name: "traps", body_group_id: back.id)
muscle16 = Muscle.create!(name: "triceps", body_group_id: arm.id)
muscle17 = Muscle.create!(name: "shoulders", body_group_id: shoulder.id)

WorkoutMuscle.create!(workout_id: tricep_dips.id, muscle_id: muscle16.id)
WorkoutMuscle.create!(workout_id: squat.id, muscle_id: muscle14.id)
WorkoutMuscle.create!(workout_id: bulgarian_split_squat.id, muscle_id: muscle8.id)
WorkoutMuscle.create!(workout_id: leg_press.id, muscle_id: muscle14.id)
WorkoutMuscle.create!(workout_id: leg_curl.id, muscle_id: muscle9.id)
WorkoutMuscle.create!(workout_id: calf_raises.id, muscle_id: muscle5.id)
WorkoutMuscle.create!(workout_id: seated_tricep_dips.id, muscle_id: muscle16.id)
WorkoutMuscle.create!(workout_id: barbell_hip_thrusts.id, muscle_id: muscle8.id)
WorkoutMuscle.create!(workout_id: barbell_curls.id, muscle_id: muscle4.id)
WorkoutMuscle.create!(workout_id: lying_oblique_reach.id, muscle_id: muscle1.id)
WorkoutMuscle.create!(workout_id: bear_crawl.id, muscle_id: muscle1.id)
WorkoutMuscle.create!(workout_id: kickbacks.id, muscle_id: muscle1.id)
WorkoutMuscle.create!(workout_id: bicycles.id, muscle_id: muscle1.id)
WorkoutMuscle.create!(workout_id: machine_flyes.id, muscle_id: muscle6.id)
WorkoutMuscle.create!(workout_id: cable_hammer_bicep_curls.id, muscle_id: muscle4.id)
WorkoutMuscle.create!(workout_id: dumbbell_flyes.id, muscle_id: muscle6.id)
WorkoutMuscle.create!(workout_id: lat_pulldown.id, muscle_id: muscle10.id)
WorkoutMuscle.create!(workout_id: barbell_clean_and_press.id, muscle_id: muscle17.id)
WorkoutMuscle.create!(workout_id: barbell_shoulder_press.id, muscle_id: muscle17.id)
WorkoutMuscle.create!(workout_id: cable_upright_rows.id, muscle_id: muscle17.id)
WorkoutMuscle.create!(workout_id: pullups.id, muscle_id: muscle10.id)
WorkoutMuscle.create!(workout_id: bar_rows.id, muscle_id: muscle12.id)
WorkoutMuscle.create!(workout_id: deadlifts.id, muscle_id: muscle11.id)
WorkoutMuscle.create!(workout_id: shoulder_shrugs.id, muscle_id: muscle13.id)

User.create!(name: "Dallin", email:"test@test.com")