arm = BodyGroup.create!(body_part: "Arms")
leg = BodyGroup.create!(body_part: "Legs")
core = BodyGroup.create!(body_part: "Core")
chest = BodyGroup.create!(body_part: "Chest")
shoulder = BodyGroup.create!(body_part: "Shoulder")
back = BodyGroup.create!(body_part: "Back")

Workout.create!(img: "https://www.mensjournal.com/.image/c_limit%2Ccs_srgb%2Cq_auto:good%2Cw_620/MTk2MTM3MzIxNzgzMDQzNTg5/2-dip.webp")

Muscle.create!(name: "abdominals", body_group_id: core.id)
Muscle.create!(name: "abductors", body_group_id: leg.id)
Muscle.create!(name: "adductors", body_group_id: leg.id)
Muscle.create!(name: "biceps", body_group_id: arm.id)
Muscle.create!(name: "calves", body_group_id: leg.id)
Muscle.create!(name: "chest", body_group_id: chest.id)
Muscle.create!(name: "forearms", body_group_id: arm.id)
Muscle.create!(name: "glutes", body_group_id: leg.id)
Muscle.create!(name: "hamstrings", body_group_id: leg.id)
Muscle.create!(name: "lats", body_group_id: back.id)
Muscle.create!(name: "lower_back", body_group_id: back.id)
Muscle.create!(name: "middle_back", body_group_id: back.id)
Muscle.create!(name: "neck", body_group_id: shoulder.id)
Muscle.create!(name: "quadriceps", body_group_id: leg.id)
Muscle.create!(name: "traps", body_group_id: back.id)
Muscle.create!(name: "triceps", body_group_id: arm.id)
